from enum import StrEnum


class GamePhase(StrEnum):
    INIT = "INIT"
    CHECK_WIN = "CHECK_WIN"
    NIGHT_START = "NIGHT_START"
    WOLF_ACTION = "WOLF_ACTION"
    SEER_ACTION = "SEER_ACTION"
    WITCH_ACTION = "WITCH_ACTION"
    NIGHT_END = "NIGHT_END"
    DAY_START = "DAY_START"
    HUNTER_SHOOTING = "HUNTER_SHOOTING"
    DEAD_LAST_WORDS = "DEAD_LAST_WORDS"
    DAY_SPEAKING = "DAY_SPEAKING"
    VOTING = "VOTING"
    VOTE_RESULT = "VOTE_RESULT"
    BANISH_LAST_WORDS = "BANISH_LAST_WORDS"
    GAME_OVER = "GAME_OVER"
